---
title: "p8105_hw3_yl2625"
author: "Yurou Liu"
date: "2025-10-07"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1
load in data

```{r}
library(dplyr)

devtools::install_github("p8105/p8105.datasets")
library(p8105.datasets)

data("instacart") 
insta_ez_to_read = instacart %>% 
  select(order_number, aisle, everything())
```

```{r}
# group by same aisles and sum up the order number for the same group 
total_aisle_df = insta_ez_to_read %>% 
  group_by(aisle) %>% 
  summarise(total_orders = sum(order_number)) %>%
  arrange(desc(total_orders))

# count the number of different aisles
num_aisles = n_distinct(total_aisle_df$aisle)

# find out the best seller
best_seller = total_aisle_df %>% 
  # pick out the aisle with the most orders, of there are aisles with the same number of orders, they will be picked out together
  filter(total_orders == max(total_orders))

print(num_aisles)
print(best_seller)
```
There are 134 different aisles, and most items are ordered form fresh fruits, with 2787084 orders in total.

### make a plot

```{r, fig.height=16, fig.width=10}
plot_df = total_aisle_df %>% 
  filter(total_orders > 10000)

library(ggplot2)

plot_df %>% 
  mutate(order_num_category = if_else(total_orders > 200000, "High", if_else(total_orders > 50000, "Medium", "Low")
  )) %>% 
  mutate(order_num_category = factor(order_num_category, levels = c("High", "Medium", "Low"))) %>% 
  ggplot(aes(y = reorder(aisle, total_orders), x = total_orders)) + 
  geom_col() +
  labs(title = "Aisles with 10000+ Orders", x = "Number of Orders", y = "Aisle") + 
  geom_text(aes(label = format(total_orders, big.mark = ",")), hjust = -.05, size = 3) + 
  facet_grid(order_num_category ~ ., scales = "free_y", space = "free_y") +
  scale_x_continuous(expand = expansion(mult = c(0, .1))) + 
  theme(plot.title = element_text(hjust = .5))
```
